spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/test
          jwk-set-uri: http://localhost:8080/realms/test/protocol/openid-connect/certs
server:
  port: 8081